#!/usr/bin/env perl
use Object::Pad ':experimental(:all)';

package Net::SSLeay::CA::Exec;

class Net::SSLeay::CA::Exec;

use utf8;
use v5.40;

use vars '@EXPORT';

@EXPORT = qw(exec);

use parent 'Exporter';

use IPC::Run3;
use List::Util 'any';

field $cmd_aref : param;
field $outbuff  : param = [];
field $errbuff  : param = [];
field $status;
field $err;

sub writeh ( $line, $handle = *STDIN, %opts ) {
    chomp $line;

    $line = "《Info》" if any { $opts{$_} == 1 } qw(info notice help);
    $line = "▶ $line"
      if any { $opts{$_} == 1 } qw(plain say print arrow right_arrow);
    $line = "❌️ $line " if any { $opts{$_} == 1 } qw(error fatal die);
    $line = "‼️ $line"  if any { $opts{$_} == 1 } qw(warn warning danger);

    say $handle->$ $line unless $opts{quiet};

    $line;
}

method fatal ( $err, $status = 255, %opts ) {
    writeh( $err, *STDERR, %opts );
}

method $outh ( $line, %opts ) {

    writeh( $line, %opts );
    push @$outbuff, $line;
}

method $errh ( $line, %opts ) {
    writeh( "$line", %opts );
    push @$errbuff, $line;
}

sub exec (
    $cmd_aref,
    $inh  = \undef,
    $outh = sub ( $self, $line ) { $self->$outh($line) },
    $errh = sub ( $self, $line ) { $self->$errh($line) }, %opts
  )
{
    my $exec = Net::SSLeay::CA::Exec->new;
    my $run3 = $exec->run3( $cmd_aref, $inh, $outh, $errh );
    fatal( "Unknown error occured while trying to run external command:\n"
          . join " @$cmd_aref" );
}

package Net::SSLeay::CA::catool;
use lib 'lib';

class Net::SSLeay::CA::catool : isa(Net::SSLeay::CA::Base)
  : abstract;    # : does(Net::SSLeay::CA);

use utf8;
use v5.40;

use Const::Fast;
use Time::Piece;
use Time::Moment;
use Net::SSLeay;
use Getopt::Long;
use Path::Tiny;
use IPC::Run3;
use Net::Domain;
use List::Util 'any';

#const our @CA_HEIRARCHY_RANK = qw(q);
field $openssl;
field $isroot = 1;
field $issub;

#field $CAkey;
field $newCAkey;

#field $CAcert;
field $newCAcert;    #//=$CAkey;
field $newCAcsr;

field $signingCA;
field $signingCAkey;
field $keyalgo = 'RSA';
field $keybits = 4096;
field $CAtop   = "ENV{HOME}/.local/ca";
field @days    = ();                      #$days;
                                          #$CA_HEIRARCHY_RANK[0];
field $CApathlen =
  $issub && !$isroot ? 0 : 1;             #$CArank ne $CA_HEIRARCHY_RANK[0];

field $CArank = 'Local';
field $CArev;

field $hostfqdn  = Net::Domain::hostfqdn;
field $localuser = `whoami`;

field $subj = (
    class {
        field $cn : param;
        field $o  : param;
        field $ou : param;
    }
)->new(
    cn => "$localuser@$hostfqdn $CArank CA 《$keyalgo$keybits✖$CArev》",
    o  => "$hostfqdn",
    ou => "Local User"
);

method run : common ($argv = \@ARGV) {
    my ( $self, $cliopts ) = $class->new->cliopts(
        argv    => $argv,
        optspec => {
            'CAcert=s',
            'CAkey=s',
            'signingCAcert=s',
            'signingCAkey=s',
            'CAcsr', 'days',
            'keyalgo',
            'keybits',
            'san|subject-alternative-name|',
            '<>' => sub ( $self, $barearg ) {
                if ( my $field = $class->isvalid($barearg) ) {
                    $self->addfield($field)
                      // fatal(
                        "Error processing '$field' as a valid SAN value");
                }
            }
        }
    );
}

method genpkey ( $algo, $bits, %opts ) {

}

method signCA {

}

method CAsign {

}

method selfsignCA {

    # `openssl x509 -req -in "$CAtop/$newCAcsr" \-copy_extensions copyall \-out
    #   "$newCAcert" \-set_subject
    #   "/CN=$cnsubj/O=$hostfqdn/OU=Local User/C=US/" \-key "$newCAkey" -
    #   days 3652`

    exec(
        [
            @$openssl,            qw(x509 -req -in),
            "$CAtop/$newCAcsr",   qw(copy_extensions copyall -out),
            $newCAcert,           '-set_subject',
            $subj->mutlivalue_SH, '-key',
            "$newCAkey",          @days
        ]
    );
}

method selfsign {

}

method x509toreq () {

}

method x509toCA () {

}

package catool;

sub run {
    Net::SSLeay::CA::catool->new( argv => \@ARGV );
}
