#!/usr/bin/env perl
use Object::Pad ':experimental(:all)';

package catool;

use lib 'lib';

class catool : does(Net::SSLeay::CA::Util);

use utf8;
use v5.40;

use File::chdir;
use Path::Tiny;
use List::Util qw'uniq any';
use Const::Fast;
use IPC::Nosh;
use IPC::Nosh::Common;
use TOML::Tiny;
use Syntax::Keyword::Dynamically;
use Syntax::Keyword::Try;
use Getopt::Long
  qw(GetOptionsFromArray :config no_ignore_case auto_abbrev passthrough long_prefix_pattern=--?);
use Pod::Usage;

use Net::SSLeay::CA::Util;

const our $CLASS_ROOT => 'Root';
const our $CLASS_SUB  => 'Subordinate';

field $class : param = $CLASS_ROOT;
field $classlvl;
field $classname : param //= $class;
field $catop : param { path( "$CWD/" . catool->hostname . '-CA' ) }
field $verbose : param = 0;
field $debug   : param = 0;

ADJUST {
    dmsg $self
}

method GetOptionsFromCLI : common ($argv = \@ARGV) {
    my %clidest = ();
    my $cmd;

    GetOptionsFromArray(
        $argv,
        \%clidest,
        'verbose+',
        'debug+', 'help|?', 'man',
        '<>' => sub ($barearg) {
            $cmd = $barearg;
        }
    ) or pod2usage(2);

    pod2usage( 1, -verbose => 1 ) if $clidest{help};
    pod2usage( -exitval => 0, -verbose => 2 ) if $clidest{man};

    my $self = $class->new(%clidest);

    fatal("$0 must be called with a command:") unless $cmd;
    $self->usage;

    $self->cmd($cmd);

    return $self;
}

method usage {

}

method cmd {
    const my %dispatch => ( new => 'newca' );
}

method newca {
    $self->export_system_trust($catop);
}

method export_system_trust ( $destdir = $catop ) {
    $destdir = path($destdir) unless $destdir isa Path::Tiny;

    dynamically $CWD = $destdir;
    $self->export_system_trust;

    my $run = run(
        [
            qw(trust extract --verbose --format=pem-directory --filter=ca-anchors --purpose=server-auth),
            "$catop/system-trust"
        ]
    );

    dmsg $run;
    $destdir;
}

method init_catop {
    const my @cadirtree = qw(private newcert crl certs db);
    $catop->mkdir;

    foreach my $dir (@cadirtree) {
        $catop->mkdir($dir);
    }
}

package main;

catool->GetOptionsFromCLI( \@ARGV )

__END__

=encoding utf8


=head1 NAME

catool is a tool for tooling around with CAs


=head1 SYNOPSIS


=head2 C<catool newca>

 
 [--class={root,(subordinate||intermediate); default="root"}
  {--name=<NAME>; default=<HOSTNAME>
   --country
   --locality
   --email
    | --subject=<ASN>
   }
  --parent=<DIR>
  --pathlen=<0-...>; default=0
  --openssl-config=<FILE>
  --certfile=<FILE>
  {--keyfile=<FILE> | --algorithm={rsa,ecc[=...]}; default="ecc=secp384r1"}
  ...]



=head2 C<catool ...> 
